# Generated by Django 3.0.6 on 2020-05-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(max_length=100000),
        ),
    ]
