# Generated by Django 3.0.6 on 2020-05-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200520_0536'),
        ('comments', '0002_auto_20200522_0157'),
        ('favorites', '0002_auto_20200519_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
